### ISSUE TITLE
the geo_localize function goes against googlemap api term of use

### ISSUE THREAD

**Issue by nbessi** [OCA/geospatial#32] opened 2015-06-02 07:27 UTC
AFAIK you are not allowed to store coordinate that are provided by google.
This must be confirmed and corrected.

**Comment by lmignon** [comment] 2015-06-02 07:40
Latitude and longitude are stored by odoo itself. As you said this must be confirmed.

**Comment by lmignon** [comment] 2015-06-02 08:43
As specified in https://developers.google.com/maps/documentation/geocoding/#Limits

> The Geocoding API may only be used in conjunction with a Google map; geocoding results without displaying them on a map is prohibited. For complete details on allowed usage, consult the Maps API Terms of Service License Restrictions.

**Comment by lmignon** [comment] 2015-06-02 08:47
More precisely: https://developers.google.com/maps/terms#section_10_1_3

> (b) No Pre-Fetching, Caching, or Storage of Content. You must not pre-fetch, cache, or store any Content, except that you may store: (i) limited amounts of Content for the purpose of improving the performance of your Maps API Implementation if you do so temporarily (and in no event for more than 30 calendar days), securely, and in a manner that does not permit use of the Content outside of the Service; and (ii) any content identifier or key that the Maps APIs Documentation specifically permits you to store. For example, you must not use the Content to create an independent database of "places" or other local listings information.

**Comment by lmignon** [comment] 2015-06-02 14:27
https://github.com/OCA/geospatial/pull/34 provides an alternative to google. The coordinates are queried using the Nominatim service offered by OpenStreetMap

**Comment by lmignon** [comment] 2015-06-03 10:26
@nbessi can be closed since #34 is merged.

**Closed as completed** 2015-06-04 07:41 UTC
