### ISSUE TITLE
No partner Map

### ISSUE THREAD

**Issue by lammh** [OCA/geospatial#71] opened 2016-02-11 20:05 UTC
I install the module geoengine_partner in odoo 8.0 but I have not received the map, the background remains white
please as I do to see the partner
![image](https://cloud.githubusercontent.com/assets/7395544/12988781/b38de2b2-d102-11e5-9aab-9cdf6a586099.png)

**Comment by foutoucour** [comment] 2016-02-12 14:01
Hello @lammh,

Do you use google map as layer?
We had the same kind of issue when we used google map and just switching to Open Street Map resolved the case.
It can be a work around if you are not in the obligation to use google map.

Hope it helps,
Jordi

**Comment by lammh** [comment] 2016-02-12 14:14
Sorry,
how a can switching in open Street Map
please

**Comment by lammh** [comment] 2016-02-12 14:19
@foutoucour  think's for your answer , but how i can get Map Snippet in our parnter
![image](https://cloud.githubusercontent.com/assets/7395544/13009267/d47dc818-d19b-11e5-8126-2a4f330dfaad.png)

**Comment by foutoucour** [comment] 2016-02-12 17:18
Sorry I can't help more on the case. You might need someone from CampToCamp
to guide you here :(

On Fri, Feb 12, 2016 at 9:19 AM lammh notifications@github.com wrote:

> @foutoucour https://github.com/foutoucour think's for your answer , but
> how i can get Map Snippet in our parnter
> [image: image]
> https://cloud.githubusercontent.com/assets/7395544/13009267/d47dc818-d19b-11e5-8126-2a4f330dfaad.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/geospatial/issues/71#issuecomment-183349274.
> 
> ## 
> 
> ---
> - Jordi Riera, Connecting Softwares and people.
>   Founder at www.cgstudiomap.org, Because everyone should be familiar with
>   the cg industry

www.linkedin.com/in/jordirieracg/ http://ca.linkedin.com/in/jordirieracg/

**Comment by yvaucher** [comment] 2016-02-15 10:18
@lammh the widget on the partner will use the first map layer configured. You should remove google map layer and only keep the OpenStreetMap one to ensure it is use in widget.

**Comment by lammh** [comment] 2016-02-15 18:52
@yvaucher , i have only OpenStreetMap
![image](https://cloud.githubusercontent.com/assets/7395544/13057591/71efa336-d41d-11e5-8f6b-82f6af662e9a.png)
@yvaucher please the steps to configure map partner,

**Comment by yvaucher** [comment] 2016-02-16 10:24
@lammh I'm not sure about what your question is. Is it that the widget in the partner form has no map or is it that you don't have a widget at all in partner form?

**Comment by lammh** [comment] 2016-02-16 10:34
@yvaucher  I don't have a widger at all in partner form

**Comment by yvaucher** [comment] 2016-02-16 10:55
@lammh Thus you need to add it.

Here is an example of how to use the widget in form:
https://github.com/OCA/geospatial/blob/8.0/base_geoengine_demo/retail_machine_view.xml#L15-L16

As this is not a bug I'm closing this issue.

**Closed as completed by yvaucher** 2016-02-16 10:55 UTC

**Comment by yvaucher** [comment] 2016-02-16 10:57
Note that google layers issue is already reported here https://github.com/OCA/geospatial/issues/63
