### ISSUE TITLE
scroll move edit map cursor

### ISSUE THREAD

**Issue by josemicopa** [OCA/geospatial#124] opened 2016-11-02 11:22 UTC
I have the map editing in a tab at the bottom, when I scroll to see the entire map the cursor moves.
without scroll:
![map1](https://cloud.githubusercontent.com/assets/23212280/19926801/f6c5f56e-a0f6-11e6-8449-df4353ec4e9d.png)

after scrolling:
![map2](https://cloud.githubusercontent.com/assets/23212280/19926804/faa73f6c-a0f6-11e6-90d3-81706da6784b.png)

**Comment by yvaucher** [comment] 2016-11-02 11:28
@joseodoo Thanks for reporting.

Are you using chrome ?

This if so this is an issue with this browser see:
https://github.com/OCA/geospatial/issues/82

Otherwise it could be a duplicate of https://github.com/OCA/geospatial/issues/122
As it is certainly a duplicate, I'm closing it.

If it is related to issue #122 , could you provide more information about your browser / OS

**Closed as completed by yvaucher** 2016-11-02 11:28 UTC
